# Generated by Django 4.2.4 on 2023-09-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_w_id_order_user_id_order_work_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hash_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_hash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_merchant_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_paid_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_payer_identifier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_payer_ip_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_payment_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_payment_desc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_payment_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_sys_payment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lmi_sys_payment_id',
        ),
    ]
